### ISSUE TITLE
    A pickle problem while running: TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by TyjChristy** [AlessandroSaviolo/Evolving-CNNs-using-GA#1]
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv2d (Conv2D)              (None, 32, 32, 32)        896
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 30, 30, 32)        9248
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 32)        0
_________________________________________________________________
flatten (Flatten)            (None, 7200)              0
_________________________________________________________________
dense (Dense)                (None, 128)               921728
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290
=================================================================
Total params: 933,162
Trainable params: 933,162
Non-trainable params: 0
_________________________________________________________________
None
FITNESS:  1.118133783340454
Traceback (most recent call last):
  File "main.py", line 216, in <module>
    main()
  File "main.py", line 181, in main
    optCNN = genetic_algorithm(num_population, num_generation, num_offspring, dataset)
  File "main.py", line 76, in genetic_algorithm
    population = initialize_population(num_population, dataset)
  File "main.py", line 15, in initialize_population
    daddy = compute_parent(dataset)                                 # load parent from input
  File "/home/guohy/ECNN/Evolving-CNNs-using-GA/src/inout.py", line 62, in compute_parent
    daddy.train_and_evaluate(model, dataset)
  File "/home/guohy/ECNN/Evolving-CNNs-using-GA/src/network.py", line 52, in train_and_evaluate
    save_network(self)                                  # save topology, model and fitness
  File "/home/guohy/ECNN/Evolving-CNNs-using-GA/src/utilities.py", line 31, in save_network
    pickle.dump(network, object_file)
TypeError: can't pickle _thread.RLock objects

Could you tell me how to solve the problem?Thank you very much.

**Comment by AlessandroSaviolo** [comment]
https://github.com/AlessandroSaviolo/Evolving-CNNs-using-GA/blob/master/src/network.py#L52

Can you try to change this line of code to `save_network(self.model)` ?

**Comment by TyjChristy** [comment]
> https://github.com/AlessandroSaviolo/Evolving-CNNs-using-GA/blob/master/src/network.py#L52
> 
> Can you try to change this line of code to `save_network(self.model)` ?


Thank you for your prompt reply.I have changed it as you said, but another problem appears:
Traceback (most recent call last):
  File "main.py", line 216, in <module>
    main()
  File "main.py", line 181, in main
    optCNN = genetic_algorithm(num_population, num_generation, num_offspring, dataset)
  File "main.py", line 76, in genetic_algorithm
    population = initialize_population(num_population, dataset)
  File "main.py", line 15, in initialize_population
    daddy = compute_parent(dataset)                                 # load parent from input
  File "/home/guohy/ECNN/Evolving-CNNs-using-GA/src/inout.py", line 62, in compute_parent
    daddy.train_and_evaluate(model, dataset)
  File "/home/guohy/ECNN/Evolving-CNNs-using-GA/src/network.py", line 52, in train_and_evaluate
    save_network(self.model)                                  # save topology, model and fitness
  File "/home/guohy/ECNN/Evolving-CNNs-using-GA/src/utilities.py", line 32, in save_network
    pickle.dump(network, object_file)
_pickle.PicklingError: Can't pickle <class 'weakref'>: attribute lookup weakref on builtins failed

It looks like the 'pilkle' problem.I try some method to modify but it still exists.Could you tell me how to solve it? Thank you very much!

**Comment by actforjason** [comment]
Here's a fix adapted from [http://zachmoshe.com/2017/04/03/pickling-keras-models.html ](http://zachmoshe.com/2017/04/03/pickling-keras-models.html )intended for solving the same issue back when Keras models used to not be pickleable.

**Comment by AlessandroSaviolo** [comment]
Thank you for posting a solution to this issue!
