### ISSUE TITLE
“Proportionate Selection” The smaller the fitness, the better, but the smaller the probability of selection.

### ISSUE THREAD

**Issue by actforjason** [AlessandroSaviolo/Evolving-CNNs-using-GA#3]
**“Proportionate Selection” The smaller the fitness, the better, but the smaller the probability of selection.**

![image](https://user-images.githubusercontent.com/57058325/105799015-6eb21b80-5fce-11eb-98bf-292907a514cf.png)

**Comment by AlessandroSaviolo** [comment]
Hi! I see no problems in the pseudo-code, can you further explain your issue?

**Comment by actforjason** [comment]
For a individual, the smaller the fitness（classification error）, the better, but the smaller fitness/sum, which means the smaller probability seleted. In fact, less fitness should have higher probability of being chosen.

**Comment by AlessandroSaviolo** [comment]
You are right. Initially I was maximizing the accuracy, that's why the proportionate selection is updated in that way. I've just updated that line of code. Let me know if it fixes the problem. Thank you for creating this issue!
