### ISSUE TITLE
question

### ISSUE THREAD

**Issue by fengyi21** [AlessandroSaviolo/Evolving-CNNs-using-GA#4]
Evolving-CNNs-using-GA/src/utilities.py", line 32, in save_network
    pickle.dump(network, object_file)
TypeError: can't pickle weakref objects
Excuse me, how to solve this problem ?

**Comment by AlessandroSaviolo** [comment]
Hi!

It looks like you have an error with the pickled object. Can you try to follow the solution proposed by the top answer here:
https://stackoverflow.com/questions/23644920/pickling-weakref-in-python

Let me know if it fixes the problem!

**Comment by fengyi21** [comment]
This problem has been solved, it is caused by the configuration version of the computer environment. 
I would like to ask another question here, how to realize the function of local picture prediction and output prediction results based on this code?

**Comment by AlessandroSaviolo** [comment]
Hi,

Happy to hear that you solved the problem with pickle!
If you want to use the learned best model for making predictions, you have to use [optCNN.model](https://github.com/AlessandroSaviolo/Evolving-CNNs-using-GA/blob/master/src/main.py#L193). There are a lot of guides online about how to make predictions using a Keras model. Have a look [here](https://stackoverflow.com/questions/37891954/keras-how-do-i-predict-after-i-trained-a-model).
